target(COMPILE_FEATURES ${PROJECT_NAME} cxx_std_17)

fetch(HUB{libssh2/libssh2@libssh2-1.8.0}
  OPTIONS
    ENABLE_ZLIB_COMPRESSION ON
    CRYPTO_BACKEND WinCNG
    BUILD_EXAMPLES OFF
    BUILD_CLAR OFF)

fetch(HUB{libgit2/libgit2@v0.28.2}
  OPTIONS
    USE_SSH OFF
    LIBSSH2_FOUND TRUE
    LIBSSH2_LIBRARIES SSH::SSH
    LIBSSH2_LIBRARY_DIRS $<TARGET_FILE_DIR:SSH::SSH>)